name: Build and Deploy Docusaurus

on:
  push:
    branches:
      - main 

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Install dependencies
      run: npm ci

    - name: Convert from notion to markdown
      run: npx @sillsdev/docu-notion -n secret_N3vSnTZoYugicDdCZOBIPzh9APT38RTdIy8USMEHx24 -r 9530c73bb3f04c358532e3f243716143
      
    - name: Build Docusaurus
      run: npm run build

    - name: Delete gh-pages branch
      run: |
        git push origin --delete gh-pages || echo "Branch not found, skipping deletion"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build

